#!/bin/bash

if [ -f /etc/debian_version ]; then
	sudo apt-get install awscli
elif [ -f /etc/redhat-release ]; then
	curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
	unzip awscli-bundle.zip
	sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
fi
